name: Continuous Integration

on: [push, pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Debug, Release]
        build_platform: [AnyCPU]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Nuget restore solution
      working-directory: OutlookRecipientCleaner/
      run: nuget restore OutlookRecipientCleaner.sln

    - name: MSBuild of solution
      working-directory: OutlookRecipientCleaner/
      run: msbuild OutlookRecipientCleaner.sln /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}" /m /verbosity:minimal /t:Publish

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
          name: OutlookRecipientCleaner_${{ matrix.build_platform }}
          path: |
              OutlookRecipientCleaner/OutlookRecipientCleaner/bin/${{ matrix.build_configuration }}-${{ matrix.build_platform }}/app.publish/
